name: Commit message format check
on:
  # ATTENTION: See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  # re security implications of using this trigger; in particular, no code from PR branches must
  # be executed in any flows triggered by it
  pull_request_target:
    branches: [ master ]

jobs:
  build:
    name: Commit message
    runs-on: ubuntu-latest
    steps:
      - name: Commit messages in format DBZ-xxx
        id: message
        env:
          pull_request_number: ${{ github.event.pull_request.number }}
        run: |
          PREFIX_CHECK=$(curl --silent -X "GET" https://api.github.com/repos/debezium/debezium/pulls/2522 | jq -r '.title' | grep -o -E -i '(^DBZ-[[:digit:]]+)|(\[release\])|(\[jenkins-jobs\])|(\[docs\])')
          if [[ $PREFIX_CHECK == "" ]]; then
            echo "::set-output name=PREFIX::false"
          fi
      - name: Create Comment
        if: ${{ steps.message.outputs.PREFIX == 'false' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hi @${{ github.event.pull_request.user.login }}, thanks for your contribution. Please prefix the commit message(s) with the [DBZ-xxx JIRA issue key](https://github.com/debezium/debezium/blob/master/CONTRIBUTE.md#making-changes).
